mod riscv_trace_shout_event_table_shared_cpu_bus_linkage_redteam;
mod riscv_trace_shout_shared_cpu_bus_linkage_redteam;
mod riscv_trace_shout_sub_shared_cpu_bus_linkage_redteam;
mod riscv_trace_shout_xor_shared_cpu_bus_linkage_redteam;
