mod memory_adversarial_tests;
mod prefix_scaling;
mod riscv_mul_decomp_perf;
mod riscv_poseidon2_ecall_perf;
mod riscv_trace_ab_perf;
mod riscv_trace_wiring_output_binding_perf;
mod single_addi_metrics_nightstream;
